/* ALL ACTIONS TO USE */

/* BASE ERASE */
const GET_INFO_REQUEST = "GET_INFO_REQUEST";
const GET_INFO_SUCCESS = "GET_INFO_SUCCESS";
const GET_INFO_ERROR = "GET_INFO_ERROR";

/* LOADER */
const SHOW_LOADER = "SHOW_LOADER";
const HIDE_LOADER = "HIDE_LOADER";

/* MODAL */
const SHOW_MODAL = "SHOW_MODAL";
const HIDE_MODAL = "HIDE_MODAL";
const ACCEPT_MODAL = "ACCEPT_MODAL";

export {
	GET_INFO_REQUEST,
	GET_INFO_SUCCESS,
	GET_INFO_ERROR,
	SHOW_LOADER,
	HIDE_LOADER,
	SHOW_MODAL,
	HIDE_MODAL,
	ACCEPT_MODAL,
};
