/* ALL ACTIONS TO USE */

/* LOADER */
const SHOW_LOADER = "SHOW_LOADER";
const HIDE_LOADER = "HIDE_LOADER";

/* MODAL */
const SHOW_MODAL = "SHOW_MODAL";
const HIDE_MODAL = "HIDE_MODAL";
const ACCEPT_MODAL = "ACCEPT_MODAL";

/* MAIN */

const GET_POKE_REQUEST = "GET_POKE_REQUEST";
const GET_POKE_SUCCESS = "GET_POKE_SUCCESS";
const GET_POKE_ERROR = "GET_POKE_ERROR";

const GET_POKE_DETAIL_REQUEST = "GET_POKE_DETAIL_REQUEST";
const GET_POKE_DETAIL_SUCCESS = "GET_POKE_DETAIL_SUCCESS";
const GET_POKE_DETAIL_ERROR = "GET_POKE_DETAIL_ERROR";

export {
	SHOW_LOADER,
	HIDE_LOADER,
	SHOW_MODAL,
	HIDE_MODAL,
	ACCEPT_MODAL,
	GET_POKE_REQUEST,
	GET_POKE_SUCCESS,
	GET_POKE_ERROR,
	GET_POKE_DETAIL_REQUEST,
	GET_POKE_DETAIL_SUCCESS,
	GET_POKE_DETAIL_ERROR,
};
